name: Daily Fear & Greed Scraper

on:
  schedule:
    # Runs at 10:30 AM, 10:50 AM, and 11:10 AM Taiwan Time (UTC+8) on weekdays (Monday to Friday)
    - cron: '30,50,10 2 * * 1-5'  # UTC time (2:30, 2:50, 3:10 UTC = 10:30, 10:50, 11:10 UTC+8)
  workflow_dispatch:  # Allows manual execution from the GitHub Actions UI

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Check out the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Use the latest stable version of Python 3

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the script with environment variables
      - name: Run script
        env:
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}  # Access the secret
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}    # Access the secret
        run: python script.py
